from enum import Enum


class Region(Enum):
    BR = 'br'
    CN = 'cn'
    EUN = 'eun'
    EUNE = 'eune'
    EUW = 'euw'
    GARENA2 = 'garena2'
    GARENA3 = 'garena3'
    ID = 'id'
    JP = 'jp'
    KR = 'kr'
    LA = 'la'
    LA1 = 'la1'
    LA2 = 'la2'
    LAN = 'lan'
    LAS = 'las'
    NA = 'na'
    OC = 'oc'
    OC1 = 'oc1'
    OCE = 'oce'
    PBE = 'pbe'
    PH = 'ph'
    RU = 'ru'
    SG = 'sg'
    TENCENT = 'tencent'
    TH = 'th'
    TR = 'tr'
    TW = 'tw'
    VN = 'vn'

class Language(Enum):
    cs_cz = 'cs_cz'
    de_de = 'de_de'
    el_gr = 'el_gr'
    en_au = 'en_au'
    en_gb = 'en_gb'
    en_ph = 'en_ph'
    en_sg = 'en_sg'
    en_us = 'en_us'
    es_ar = 'es_ar'
    es_es = 'es_es'
    es_mx = 'es_mx'
    fr_fr = 'fr_fr'
    hu_hu = 'hu_hu'
    id_id = 'id_id'
    it_it = 'it_it'
    ja_jp = 'ja_jp'
    ko_kr = 'ko_kr'
    ms_my = 'ms_my'
    pl_pl = 'pl_pl'
    pt_br = 'pt_br'
    ro_ro = 'ro_ro'
    ru_ru = 'ru_ru'
    th_th = 'th_th'
    tr_tr = 'tr_tr'
    vn_vn = 'vn_vn'
    zh_cn = 'zh_cn'
    zh_my = 'zh_my'
    zh_tw = 'zh_tw'
